# Generated by Django 4.1.3 on 2023-02-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
